import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import { UserProvider } from "./context/UserContext";
import ThemeSwitcher from "./ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      className="h-screen max-w-full"
    >
      <body className={`${inter.className} dark:bg-primary h-full`}>
        <UserProvider>
          <ThemeSwitcher />
          <main className="flex flex-col h-full container mx-auto px-4">
            {children}
          </main>
        </UserProvider>
      </body>
    </html>
  );
}
